### ISSUE TITLE
Editing existing listing 

### ISSUE THREAD

**Issue by leesheppard** [tarun-pacifica/propertyser#11]
Editing a current listing, the form does not display the correct data already entered for the listing. 

**Listing** displays like this (won't display a - symbol between one and three in heading either): 
![Screenshot 2024-10-06 at 23-13-08 Ruyi Realty](https://github.com/user-attachments/assets/b35d57af-0005-45c5-bfc4-64084494a4e6)

**Editing** page
![Screenshot 2024-10-06 at 23-12-48 Ruyi Realty](https://github.com/user-attachments/assets/8c6bbfaa-196f-4288-a0da-75daa825c920)

**Comment by tarun-pacifica** [comment]
fixed
