### ISSUE TITLE
dropdown positioning on desktop view

### ISSUE THREAD

**Issue by pacificalabs** [tarun-pacifica/propertyser#3]
<img width="1680" alt="Screenshot 2024-09-10 at 12 48 08 pm" src="https://github.com/user-attachments/assets/1bacf865-b53d-4519-8dbb-26ee32a1bc9f">

**Comment by tarun-pacifica** [comment]
<img width="1680" alt="Screenshot 2024-09-15 at 6 21 00 pm" src="https://github.com/user-attachments/assets/16fe0e9b-d10c-476f-be88-ed0c73abdd05">
