### ISSUE TITLE
Editing property doesn't save all fields

### ISSUE THREAD

**Issue by leesheppard** [tarun-pacifica/propertyser#4]
Go to staging site: [staging.ruyirealty.net.au](https://staging.ruyirealty.net.au)

1. Edit the Rouse Hill entry. 
2. Modify the bathrooms and Parking space fields. 
3. Submit and check entry. 

Neither field updates with changes.

Map does not update.

**Comment by tarun-pacifica** [comment]
@leesheppard please retest now, from my side it works...
